image: node:11

cache:
  paths:
    - node_modules
    - .yarn-cache

stages:
  - test
  - deploy-storybook

test:
  stage: test
  before_script:
    - yarn config set cache-folder .yarn-cache
    - yarn install
  script:
    - yarn lint
    - yarn test --coverage
    - yarn build

deploy-storybook:
  stage: deploy-storybook
  only:
    - master
  before_script:
    - yarn config set cache-folder .yarn-cache
    - yarn install
  script:
    - git remote add gh-pages git@github.com:woozyking/use-cached.git
    - yarn deploy-storybook --ci --remote gh-pages --branch gh-pages 1> /dev/null
