name: Node.js Lint, Test and Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12.x', '14.x']

    name: lint with Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Cache Node Modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-${{ matrix.node }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-${{ matrix.node }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-${{ matrix.node }}-build-
            ${{ runner.OS }}-${{ matrix.node }}-
            ${{ runner.OS }}-

      - run: yarn install
      - run: yarn lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12.x', '14.x']

    name: test with Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Cache Node Modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-${{ matrix.node }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-${{ matrix.node }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-${{ matrix.node }}-build-
            ${{ runner.OS }}-${{ matrix.node }}-
            ${{ runner.OS }}-

      - run: yarn install
      - run: yarn test --coverage

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12.x', '14.x']

    name: build with Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Cache Node Modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-${{ matrix.node }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-${{ matrix.node }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-${{ matrix.node }}-build-
            ${{ runner.OS }}-${{ matrix.node }}-
            ${{ runner.OS }}-

      - run: yarn install
      - run: yarn build
